### ISSUE TITLE
Kompatible mit WR105S1

### ISSUE THREAD

**Issue by bunni1310** [ldittmar81/ioBroker.landroid#12]
Hallo,
wäre super wenn Du es mit dem Landroid S WR105S1 (S500i) kompatible machen würdest,
für den wird kein Pin sondern die Seriennummer benötigt.

**Comment by ldittmar81** [comment]
Für den Landroid S existiet bereits ein anderen Adapter.

https://github.com/MeisterTR/ioBroker.landroid-s
